### ISSUE TITLE
Battery running out quickly.

### ISSUE THREAD

**Issue by unl1k3ly** [anha1/fitbit-acidclock#1]
Firstly, I pretty much appreciate your work and design! The clock face looks and works awesome.

However, I noticed the battery is been running out quickly after the install. Do you get the same on yours?

Cheers

**Comment by anha1** [comment]
Hello, @unl1k3ly 
I'm a user of AcidClock + Versa for a long time, now with the Cryptocurrency feature enabled on my device.

During this time, I experienced a battery drain issue only once - the rate of the drain was ridiculously high, like 2% per minute. Not sure regarding the cause of the issue and it was fixed after Versa's reboot.

Other than that, even with the Cryptocurrency feature enabled (Fitbit's app "All-Day Sync", "Always Connected", and notifications are also enabled), I do not experience any battery issues: the device lasts for several days without charging.

Could you please clarify:
1) was the Cryptocurrency feature enabled on your device?
2) what was the approximate rate of the battery drain?

**Comment by unl1k3ly** [comment]
Hi @anha1  I've debugged it further and problem seems to be related with a BT malfunction or something else I don't know! Good thing is that, after a hard reboot, the watch seems to be back to normal again. Thank you for your support and work mate.

In regarding to your Cryptocurrency feature, I don't get it from Fitbit Clock Faces do I ? It seems your repo is up-to-date but not the face in-store at Fitbit. Are you considering pushing new changes to the public ?

Once again, thank you so much for your work and dedication. It's much appreciated.

Cheers

**Comment by anha1** [comment]
@unl1k3ly ,
I'm always pushing repo updates once an update is approved by Fitbit and published. I'm also using a regular version from the store and the CC feature is present there.

1. Possibly, a manual update is required through Fitbit's app.
2. This feature is disabled by default and should be enabled in settings.
