### ISSUE TITLE
Stuck on 8888 placeholder

### ISSUE THREAD

**Issue by XP1** [anha1/fitbit-acidclock#3]
Stuck on 8888 placeholder

This started happening a couple days ago. Could an update have broken something?

![Fitbit AcidClock 8888 placeholder](https://user-images.githubusercontent.com/776585/97786518-82421780-1b82-11eb-940e-23f6a4d08922.jpg)

**Comment by XP1** [comment]
Fitbit must have broken the permissions during sync. I was able to fix the problem by toggling off the permissions, resyncing, toggling on the permissions, and then finally resyncing again.

I have added a troubleshooting tip to the README:
https://github.com/anha1/fitbit-acidclock/pull/4

**Comment by anha1** [comment]
@XP1 , several users reported this issue after the latest update :( . There is a problem with "Create Exercise" permission, while my code checked "if(exercise)" in proper places, any interaction with this "exercise" object causes an error (possibly a Fitbit API 4.2 regression). I committed the fix and submitted a new build for Fitbit review.

**Comment by anha1** [comment]
Missing permissions handling fix for all builds was published.
